# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import arkhe_network_pb2 as arkhe__network__pb2

GRPC_GENERATED_VERSION = '1.60.0'
GRPC_VERSION = grpc.__version__


class ArkheHypergraphStub(object):
    """ARKHE(N) HYPERGRAPH NETWORK PROTOCOL
    "A linguagem universal do vácuo informacional."

    Serviço Central de Consenso e Coerência
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitHandover = channel.unary_unary(
                '/arkhenet.ArkheHypergraph/SubmitHandover',
                request_serializer=arkhe__network__pb2.HandoverRequest.SerializeToString,
                response_deserializer=arkhe__network__pb2.HandoverResponse.FromString,
                _registered_method=True)
        self.QckdExchange = channel.unary_unary(
                '/arkhenet.ArkheHypergraph/QckdExchange',
                request_serializer=arkhe__network__pb2.QckdBasisRequest.SerializeToString,
                response_deserializer=arkhe__network__pb2.QckdBasisResponse.FromString,
                _registered_method=True)
        self.GetNodeCoherence = channel.unary_unary(
                '/arkhenet.ArkheHypergraph/GetNodeCoherence',
                request_serializer=arkhe__network__pb2.NodeIdentity.SerializeToString,
                response_deserializer=arkhe__network__pb2.CoherenceMetrics.FromString,
                _registered_method=True)


class ArkheHypergraphServicer(object):
    """ARKHE(N) HYPERGRAPH NETWORK PROTOCOL
    "A linguagem universal do vácuo informacional."

    Serviço Central de Consenso e Coerência
    """

    def SubmitHandover(self, request, context):
        """Proposta de um novo bloco minerado (Handover Global)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QckdExchange(self, request, context):
        """QCKD - Distribuição de Chave de Coerência
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeCoherence(self, request, context):
        """Consulta a Coerência Global de um nó vizinho
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArkheHypergraphServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitHandover': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitHandover,
                    request_deserializer=arkhe__network__pb2.HandoverRequest.FromString,
                    response_serializer=arkhe__network__pb2.HandoverResponse.SerializeToString,
            ),
            'QckdExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.QckdExchange,
                    request_deserializer=arkhe__network__pb2.QckdBasisRequest.FromString,
                    response_serializer=arkhe__network__pb2.QckdBasisResponse.SerializeToString,
            ),
            'GetNodeCoherence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeCoherence,
                    request_deserializer=arkhe__network__pb2.NodeIdentity.FromString,
                    response_serializer=arkhe__network__pb2.CoherenceMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arkhenet.ArkheHypergraph', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arkhenet.ArkheHypergraph', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArkheHypergraph(object):
    """ARKHE(N) HYPERGRAPH NETWORK PROTOCOL
    "A linguagem universal do vácuo informacional."

    Serviço Central de Consenso e Coerência
    """

    @staticmethod
    def SubmitHandover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhenet.ArkheHypergraph/SubmitHandover',
            arkhe__network__pb2.HandoverRequest.SerializeToString,
            arkhe__network__pb2.HandoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QckdExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhenet.ArkheHypergraph/QckdExchange',
            arkhe__network__pb2.QckdBasisRequest.SerializeToString,
            arkhe__network__pb2.QckdBasisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeCoherence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhenet.ArkheHypergraph/GetNodeCoherence',
            arkhe__network__pb2.NodeIdentity.SerializeToString,
            arkhe__network__pb2.CoherenceMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
