// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"context"
	"fmt"
	"net/url"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
)

type HandoverServiceClient interface {
	SyncContext(ctx context.Context, requestArg HandoverRequest) (HandoverResponse, error)
	StreamHandover(ctx context.Context, handoverArg HandoverRequest) (HandoverStatus, error)
}

type handoverServiceClient struct {
	client httpclient.Client
}

func NewHandoverServiceClient(client httpclient.Client) HandoverServiceClient {
	return &handoverServiceClient{client: client}
}

func (c *handoverServiceClient) SyncContext(ctx context.Context, requestArg HandoverRequest) (HandoverResponse, error) {
	var returnVal *HandoverResponse
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("SyncContext"))
	requestParams = append(requestParams, httpclient.WithPathf("/handover/sync"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(HandoverResponse), werror.WrapWithContextParams(ctx, err, "syncContext failed")
	}
	if returnVal == nil {
		return *new(HandoverResponse), werror.ErrorWithContextParams(ctx, "syncContext response cannot be nil")
	}
	return *returnVal, nil
}

func (c *handoverServiceClient) StreamHandover(ctx context.Context, handoverArg HandoverRequest) (HandoverStatus, error) {
	var returnVal *HandoverStatus
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("StreamHandover"))
	requestParams = append(requestParams, httpclient.WithPathf("/handover/stream"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(handoverArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(HandoverStatus), werror.WrapWithContextParams(ctx, err, "streamHandover failed")
	}
	if returnVal == nil {
		return *new(HandoverStatus), werror.ErrorWithContextParams(ctx, "streamHandover response cannot be nil")
	}
	return *returnVal, nil
}

type TemporalServiceClient interface {
	Emit(ctx context.Context, orbArg Orb) (CoherenceMetric, error)
	Observe(ctx context.Context, idArg string) (Orb, error)
	Collapse(ctx context.Context, idArg string) (bool, error)
	Quantize(ctx context.Context, trajectoryArg TemporalTrajectory) ([]Orb, error)
}

type temporalServiceClient struct {
	client httpclient.Client
}

func NewTemporalServiceClient(client httpclient.Client) TemporalServiceClient {
	return &temporalServiceClient{client: client}
}

func (c *temporalServiceClient) Emit(ctx context.Context, orbArg Orb) (CoherenceMetric, error) {
	var returnVal *CoherenceMetric
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Emit"))
	requestParams = append(requestParams, httpclient.WithPathf("/temporal/emit"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(orbArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(CoherenceMetric), werror.WrapWithContextParams(ctx, err, "emit failed")
	}
	if returnVal == nil {
		return *new(CoherenceMetric), werror.ErrorWithContextParams(ctx, "emit response cannot be nil")
	}
	return *returnVal, nil
}

func (c *temporalServiceClient) Observe(ctx context.Context, idArg string) (Orb, error) {
	var returnVal *Orb
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Observe"))
	requestParams = append(requestParams, httpclient.WithPathf("/temporal/observe/%s", url.PathEscape(fmt.Sprint(idArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Orb), werror.WrapWithContextParams(ctx, err, "observe failed")
	}
	if returnVal == nil {
		return *new(Orb), werror.ErrorWithContextParams(ctx, "observe response cannot be nil")
	}
	return *returnVal, nil
}

func (c *temporalServiceClient) Collapse(ctx context.Context, idArg string) (bool, error) {
	var returnVal *bool
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Collapse"))
	requestParams = append(requestParams, httpclient.WithPathf("/temporal/collapse/%s", url.PathEscape(fmt.Sprint(idArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(bool), werror.WrapWithContextParams(ctx, err, "collapse failed")
	}
	if returnVal == nil {
		return *new(bool), werror.ErrorWithContextParams(ctx, "collapse response cannot be nil")
	}
	return *returnVal, nil
}

func (c *temporalServiceClient) Quantize(ctx context.Context, trajectoryArg TemporalTrajectory) ([]Orb, error) {
	var returnVal []Orb
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Quantize"))
	requestParams = append(requestParams, httpclient.WithPathf("/temporal/quantize"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(trajectoryArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return nil, werror.WrapWithContextParams(ctx, err, "quantize failed")
	}
	if returnVal == nil {
		return nil, werror.ErrorWithContextParams(ctx, "quantize response cannot be nil")
	}
	return returnVal, nil
}
