// Code generated by conjure-go. DO NOT EDIT.

package api

import (
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type AgentCard struct {
	Name             string   `json:"name"`
	Skills           []string `json:"skills"`
	Endpoint         string   `json:"endpoint"`
	IdentityTraces   []string `json:"identityTraces"`
	AuthRequirements string   `json:"authRequirements"`
}

func (o AgentCard) MarshalJSON() ([]byte, error) {
	if o.Skills == nil {
		o.Skills = make([]string, 0)
	}
	if o.IdentityTraces == nil {
		o.IdentityTraces = make([]string, 0)
	}
	type _tmpAgentCard AgentCard
	return safejson.Marshal(_tmpAgentCard(o))
}

func (o *AgentCard) UnmarshalJSON(data []byte) error {
	type _tmpAgentCard AgentCard
	var rawAgentCard _tmpAgentCard
	if err := safejson.Unmarshal(data, &rawAgentCard); err != nil {
		return err
	}
	if rawAgentCard.Skills == nil {
		rawAgentCard.Skills = make([]string, 0)
	}
	if rawAgentCard.IdentityTraces == nil {
		rawAgentCard.IdentityTraces = make([]string, 0)
	}
	*o = AgentCard(rawAgentCard)
	return nil
}

func (o AgentCard) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *AgentCard) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CoherenceMetric struct {
	GlobalR    float64 `json:"globalR"`
	NodeLambda float64 `json:"nodeLambda"`
	Stable     bool    `json:"stable"`
}

func (o CoherenceMetric) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CoherenceMetric) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type HandoverRequest struct {
	Id             int    `json:"id"`
	TargetNode     string `json:"targetNode"`
	ContextSummary string `json:"contextSummary"`
	Priority       string `json:"priority"`
}

func (o HandoverRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *HandoverRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type HandoverResponse struct {
	Status     string  `json:"status"`
	HandoverId string  `json:"handoverId"`
	PhiRemote  float64 `json:"phiRemote"`
}

func (o HandoverResponse) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *HandoverResponse) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type HandoverStatus struct {
	Success bool    `json:"success"`
	Phi     float64 `json:"phi"`
}

func (o HandoverStatus) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *HandoverStatus) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type Orb struct {
	Id        string  `json:"id"`
	Lambda2   float64 `json:"lambda2"`
	PhiQ      float64 `json:"phiQ"`
	HValue    float64 `json:"hValue"`
	Timestamp string  `json:"timestamp"`
}

func (o Orb) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Orb) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type TemporalTrajectory struct {
	Points    []float64 `json:"points"`
	Curvature float64   `json:"curvature"`
}

func (o TemporalTrajectory) MarshalJSON() ([]byte, error) {
	if o.Points == nil {
		o.Points = make([]float64, 0)
	}
	type _tmpTemporalTrajectory TemporalTrajectory
	return safejson.Marshal(_tmpTemporalTrajectory(o))
}

func (o *TemporalTrajectory) UnmarshalJSON(data []byte) error {
	type _tmpTemporalTrajectory TemporalTrajectory
	var rawTemporalTrajectory _tmpTemporalTrajectory
	if err := safejson.Unmarshal(data, &rawTemporalTrajectory); err != nil {
		return err
	}
	if rawTemporalTrajectory.Points == nil {
		rawTemporalTrajectory.Points = make([]float64, 0)
	}
	*o = TemporalTrajectory(rawTemporalTrajectory)
	return nil
}

func (o TemporalTrajectory) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *TemporalTrajectory) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
