pub mod kernel;
pub mod drivers;
pub mod neural;
pub mod physics;
pub mod topology;
pub mod compiler;
pub mod db;
pub mod net;
pub mod phys;
pub mod amt;
pub mod hmt;
pub mod maestro;
pub mod observability;
pub mod telemetry;
pub mod sensors;
pub mod quantum;
pub mod lmt;
pub mod security;
pub mod intention;
pub mod zkproof;
pub mod anchor;
pub mod week5;
pub mod physical;
pub mod rio;
pub mod wearable;
pub mod temporal;
pub mod propagation;
pub mod bridge;
pub mod orb;
pub mod bridge;
pub mod temporal;
pub mod propagation;
pub mod bridge;
pub mod orb;
pub mod bridge;
pub mod temporal;
pub mod propagation;

pub use kernel::task::Task;
pub use kernel::scheduler::{CoherenceScheduler, SchedulerEvent};
pub use physics::miller::{PHI_Q, check_nucleation, quantum_interest};
pub use physics::berry;
pub use compiler::parser::parse_intention_block;
pub use db::ledger::TeknetLedger;
pub use net::node::P2PNode;
pub use phys::ibm_client::QuantumAntenna;

#[cfg(test)]
mod tests;
#[cfg(test)]
mod physical_tests;
