# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arkhe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'arkhe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61rkhe.proto\x12\x05\x61rkhe\"\x1f\n\x0fHandoverRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x0f\n\rStatusRequest\".\n\x0eStatusResponse\x12\x0b\n\x03phi\x18\x01 \x01(\x01\x12\x0f\n\x07\x65ntropy\x18\x02 \x01(\x01\"O\n\x0fOntologyRequest\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x13\n\x0bobject_type\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\"1\n\rArkheResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc6\x01\n\x0c\x41rkheService\x12<\n\x0cSendHandover\x12\x16.arkhe.HandoverRequest\x1a\x14.arkhe.ArkheResponse\x12\x38\n\tGetStatus\x12\x14.arkhe.StatusRequest\x1a\x15.arkhe.StatusResponse\x12>\n\x0eUpdateOntology\x12\x16.arkhe.OntologyRequest\x1a\x14.arkhe.ArkheResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arkhe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDOVERREQUEST']._serialized_start=22
  _globals['_HANDOVERREQUEST']._serialized_end=53
  _globals['_STATUSREQUEST']._serialized_start=55
  _globals['_STATUSREQUEST']._serialized_end=70
  _globals['_STATUSRESPONSE']._serialized_start=72
  _globals['_STATUSRESPONSE']._serialized_end=118
  _globals['_ONTOLOGYREQUEST']._serialized_start=120
  _globals['_ONTOLOGYREQUEST']._serialized_end=199
  _globals['_ARKHERESPONSE']._serialized_start=201
  _globals['_ARKHERESPONSE']._serialized_end=250
  _globals['_ARKHESERVICE']._serialized_start=253
  _globals['_ARKHESERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
