# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import arkhe_pb2 as arkhe__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arkhe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArkheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHandover = channel.unary_unary(
                '/arkhe.ArkheService/SendHandover',
                request_serializer=arkhe__pb2.HandoverRequest.SerializeToString,
                response_deserializer=arkhe__pb2.ArkheResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/arkhe.ArkheService/GetStatus',
                request_serializer=arkhe__pb2.StatusRequest.SerializeToString,
                response_deserializer=arkhe__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateOntology = channel.unary_unary(
                '/arkhe.ArkheService/UpdateOntology',
                request_serializer=arkhe__pb2.OntologyRequest.SerializeToString,
                response_deserializer=arkhe__pb2.ArkheResponse.FromString,
                _registered_method=True)


class ArkheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendHandover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOntology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArkheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHandover': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHandover,
                    request_deserializer=arkhe__pb2.HandoverRequest.FromString,
                    response_serializer=arkhe__pb2.ArkheResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=arkhe__pb2.StatusRequest.FromString,
                    response_serializer=arkhe__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateOntology': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOntology,
                    request_deserializer=arkhe__pb2.OntologyRequest.FromString,
                    response_serializer=arkhe__pb2.ArkheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arkhe.ArkheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arkhe.ArkheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArkheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendHandover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.ArkheService/SendHandover',
            arkhe__pb2.HandoverRequest.SerializeToString,
            arkhe__pb2.ArkheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.ArkheService/GetStatus',
            arkhe__pb2.StatusRequest.SerializeToString,
            arkhe__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOntology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arkhe.ArkheService/UpdateOntology',
            arkhe__pb2.OntologyRequest.SerializeToString,
            arkhe__pb2.ArkheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
