apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkhen-retro.fullname" . }}
  labels:
    {{- include "arkhen-retro.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: rest
      protocol: TCP
      name: rest
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "arkhen-retro.selectorLabels" . | nindent 4 }}
