# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arkhe_network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'arkhe_network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61rkhe_network.proto\x12\x08\x61rkhenet\"}\n\x0fHandoverRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nblock_hash\x18\x02 \x01(\t\x12\x14\n\x0cphi_achieved\x18\x03 \x01(\x01\x12\x12\n\nnonce_time\x18\x04 \x01(\x01\x12\x1b\n\x13safe_core_signature\x18\x05 \x01(\x0c\"Q\n\x10HandoverResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12network_phi_target\x18\x03 \x01(\x01\";\n\x10QckdBasisRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x16\n\x0e\x62\x61sis_sequence\x18\x02 \x01(\x0c\"I\n\x11QckdBasisResponse\x12\x16\n\x0ematching_bases\x18\x01 \x01(\x0c\x12\x1c\n\x14\x62\x65ll_violation_score\x18\x02 \x01(\x01\"\x1f\n\x0cNodeIdentity\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"_\n\x10\x43oherenceMetrics\x12\x13\n\x0b\x63urrent_phi\x18\x01 \x01(\x01\x12\x1c\n\x14\x61\x63tive_entanglements\x18\x02 \x01(\x05\x12\x18\n\x10operational_mode\x18\x03 \x01(\t2\xf1\x01\n\x0f\x41rkheHypergraph\x12I\n\x0eSubmitHandover\x12\x19.arkhenet.HandoverRequest\x1a\x1a.arkhenet.HandoverResponse\"\x00\x12I\n\x0cQckdExchange\x12\x1a.arkhenet.QckdBasisRequest\x1a\x1b.arkhenet.QckdBasisResponse\"\x00\x12H\n\x10GetNodeCoherence\x12\x16.arkhenet.NodeIdentity\x1a\x1a.arkhenet.CoherenceMetrics\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arkhe_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDOVERREQUEST']._serialized_start=33
  _globals['_HANDOVERREQUEST']._serialized_end=158
  _globals['_HANDOVERRESPONSE']._serialized_start=160
  _globals['_HANDOVERRESPONSE']._serialized_end=241
  _globals['_QCKDBASISREQUEST']._serialized_start=243
  _globals['_QCKDBASISREQUEST']._serialized_end=302
  _globals['_QCKDBASISRESPONSE']._serialized_start=304
  _globals['_QCKDBASISRESPONSE']._serialized_end=377
  _globals['_NODEIDENTITY']._serialized_start=379
  _globals['_NODEIDENTITY']._serialized_end=410
  _globals['_COHERENCEMETRICS']._serialized_start=412
  _globals['_COHERENCEMETRICS']._serialized_end=507
  _globals['_ARKHEHYPERGRAPH']._serialized_start=510
  _globals['_ARKHEHYPERGRAPH']._serialized_end=751
# @@protoc_insertion_point(module_scope)
